name: dust
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - astroid=2.4.2=py38_0
  - astropy=4.0.1.post1=py38h7b6447c_1
  - attrs=19.3.0=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.5=py_0
  - brotlipy=0.7.0=py38h7b6447c_1000
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py38_0
  - cffi=1.14.0=py38he30daa8_1
  - chardet=3.0.4=py38_1003
  - cryptography=2.9.2=py38h1ba5d50_0
  - cycler=0.10.0=py38_0
  - dbus=1.13.14=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_0
  - expat=2.2.6=he6710b0_0
  - flake8=3.7.9=py38_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.2=h5ab3b9f_0
  - glib=2.63.1=h3eb4bd4_1
  - gmp=6.1.2=h6c8ec71_1
  - greenlet=0.4.16=py38h7b6447c_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - icu=58.2=he6710b0_3
  - idna=2.9=py_1
  - importlib-metadata=1.6.1=py38_0
  - importlib_metadata=1.6.1=0
  - intel-openmp=2020.1=217
  - ipykernel=5.3.0=py38h5ca1d4c_0
  - ipython=7.15.0=py38_0
  - ipython_genutils=0.2.0=py38_0
  - isort=4.3.21=py38_0
  - jedi=0.17.1=py38_0
  - jinja2=2.11.2=py_0
  - joblib=0.16.0=py_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.5=py_0
  - jsonschema=3.2.0=py38_0
  - jupyter_client=6.1.3=py_0
  - jupyter_core=4.6.3=py38_0
  - jupyterlab=1.2.6=pyhf63ae98_0
  - jupyterlab_server=1.1.5=py_0
  - kiwisolver=1.2.0=py38hfd86e86_0
  - lazy-object-proxy=1.4.3=py38h7b6447c_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h7b6447c_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.10=he19cac6_1
  - markupsafe=1.1.1=py38h7b6447c_0
  - matplotlib=3.1.3=py38_0
  - matplotlib-base=3.1.3=py38hef1b27d_0
  - mccabe=0.6.1=py38_1
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2020.1=217
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.1.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - msgpack-python=1.0.0=py38hfd86e86_1
  - nbconvert=5.6.1=py38_0
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he6710b0_1
  - neovim=0.3.1=py38h32f6830_1
  - notebook=6.0.3=py38_0
  - numpy=1.18.1=py38h4f9e942_0
  - numpy-base=1.18.1=py38hde5b4d6_1
  - openssl=1.1.1g=h7b6447c_0
  - packaging=20.4=py_0
  - pandas=1.0.3=py38h0573a6f_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py38_1
  - parso=0.7.0=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pip=20.1.1=py38_1
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.5=py_0
  - ptyprocess=0.6.0=py38_0
  - pycodestyle=2.5.0=py38_0
  - pycparser=2.20=py_0
  - pyflakes=2.1.1=py38_0
  - pygments=2.6.1=py_0
  - pylint=2.5.2=py38_0
  - pynvim=0.4.1=py38h32f6830_1
  - pyopenssl=19.1.0=py38_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.16.0=py38h7b6447c_0
  - pysocks=1.7.1=py38_0
  - python=3.8.3=hcff3b4d_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=py_0
  - pyzmq=18.1.1=py38he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=py38_0
  - scikit-learn=0.23.1=py38h423224d_0
  - scipy=1.4.1=py38h0b6359f_0
  - seaborn=0.10.1=py_0
  - send2trash=1.5.0=py38_0
  - setuptools=47.3.0=py38_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py_0
  - sqlite=3.32.2=h62c20be_0
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.0=py_0
  - tornado=6.0.4=py38h7b6447c_1
  - traitlets=4.3.3=py38_0
  - urllib3=1.25.9=py_0
  - wcwidth=0.2.4=py_0
  - webencodings=0.5.1=py38_1
  - wheel=0.34.2=py38_0
  - wrapt=1.11.2=py38h7b6447c_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.1=he6710b0_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - pluggy==0.13.1
    - python-jsonrpc-server==0.3.4
    - python-language-server==0.33.0
    - ujson==1.35
prefix: /home/ksuchak/anaconda3/envs/dust
